/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dfa05;

import java.io.File;
import java.net.URL;
import java.util.Arrays;
import javax.swing.text.DefaultCaret;

public class FrameMain extends javax.swing.JFrame {

    DFA dfa;
    public FrameMain() {
        initComponents();
        dfa = new DFA(outputArea);
        
        // set caret to end position to auto-scroll
        DefaultCaret caret = (DefaultCaret)outputArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE); 
        
        fileComboBox.removeAllItems();
        File[] listOfFiles = (new File("data/")).listFiles();

        // scan dir for files, add them to combobox
        Arrays.sort(listOfFiles);
        for (File file : listOfFiles) {
            if (file.getName().contains("dfa")) {
                fileComboBox.addItem(file.getName()); // ignore random files, only DFA
            }
        }
        
       /* In in;
        for (int i = 0; i < 17; i++) {
            try {
                String s;
                in = new In("data/" + fileComboBox.getItemAt(2+i));
                
                if (in.exists()) {
                    s = in.readAll();
                    outputArea.append(fileComboBox.getItemAt(2+i) + ": " + dfa.validate(s) +"\n");
                    System.out.println(fileComboBox.getItemAt(2+i) + ": " + dfa.validate(s));
                }
            }
            catch (Exception e) {
                outputArea.setText("Error in File System trying to open " + 
                fileComboBox.getSelectedItem() + "\n");
            }
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        rffButton = new javax.swing.JButton();
        fileComboBox = new javax.swing.JComboBox<>();
        validButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        rffButton.setText("Read From File");
        rffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rffButtonActionPerformed(evt);
            }
        });

        fileComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        validButton.setText("Check Validity");
        validButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fileComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rffButton))
                    .addComponent(validButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rffButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rffButtonActionPerformed
        In in = null;
        if (!((String)fileComboBox.getSelectedItem()).contains("http")) { // check for web URL
            try {
                in = new In("data/" + fileComboBox.getSelectedItem());
            }
            catch (Exception e) {
                outputArea.setText("Error in File System trying to open " + 
                fileComboBox.getSelectedItem() + "\n");
            }
            if (in != null && in.exists()) {
                outputArea.setText(in.readAll().trim() + "\n");
            }
        } else {
            try {
                in = new In(new URL((String)fileComboBox.getSelectedItem()));
                outputArea.setText(in.readAll().trim());
            }
            catch (Exception e) {
                outputArea.setText("Failed to read from " + fileComboBox.getSelectedItem() + "\n");
            }
        }
    }//GEN-LAST:event_rffButtonActionPerformed

    private void validButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validButtonActionPerformed
        outputArea.append(dfa.validate(outputArea.getText()));
    }//GEN-LAST:event_validButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("a".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> fileComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JButton rffButton;
    private javax.swing.JButton validButton;
    // End of variables declaration//GEN-END:variables
}
